services:
  - type: web
    name: page-pulse-backend
    env: node
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
